name: Publish @infrakit/ui

on:
  push:
    tags:
      - ui-v*

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/ui/core
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Set package version from tag
        id: version
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"
          VERSION="${TAG_NAME#ui-v}"
          if [ -z "$VERSION" ] || [ "$VERSION" = "$TAG_NAME" ]; then
            echo "Tag '$TAG_NAME' does not follow the expected 'ui-v*' pattern."
            exit 1
          fi
          export VERSION
          bun --eval "const fs = require('fs'); const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8')); pkg.version = process.env.VERSION; fs.writeFileSync('package.json', JSON.stringify(pkg, null, '\t') + '\n');"

      - name: Build package
        run: bun run build

      - name: Publish to npm
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun publish --access public
